// MongoDB Playground
// Use Ctrl+Space inside a snippet or a string literal to trigger completions.

// The current database to use.
use("db_clinic_managment");

const patientData =
    [
        {
            firstName: "Ali",
            lastName: "Khan",
            phone: "+923001234567",
            email: "ali.khan1@example.com",
            address: "12 Street 3, Karachi",
            age: 25,
            gender: "Male",
            emergencyContact: "Sara Ahmed",
            emergencyPhone: "+923009876543",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Sara",
            lastName: "Ahmed",
            phone: "+923002345678",
            email: "sara.ahmed2@example.com",
            address: "45 Street 1, Lahore",
            age: 32,
            gender: "Female",
            emergencyContact: "Bilal Hussain",
            emergencyPhone: "+923001112233",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Ahmed",
            lastName: "Hussain",
            phone: "+923003456789",
            email: "ahmed.hussain3@example.com",
            address: "78 Street 4, Islamabad",
            age: 40,
            gender: "Male",
            emergencyContact: "Zara Ali",
            emergencyPhone: "+923004556677",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Zara",
            lastName: "Ali",
            phone: "+923004567890",
            email: "zara.ali4@example.com",
            address: "23 Street 2, Karachi",
            age: 28,
            gender: "Female",
            emergencyContact: "Hassan Malik",
            emergencyPhone: "+923005667788",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Hassan",
            lastName: "Raza",
            phone: "+923005678901",
            email: "hassan.raza5@example.com",
            address: "56 Street 5, Multan",
            age: 35,
            gender: "Male",
            emergencyContact: "Fatima Shah",
            emergencyPhone: "+923006778899",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Ayesha",
            lastName: "Qureshi",
            phone: "+923006789012",
            email: "ayesha.qureshhi6@example.com",
            address: "89 Street 3, Rawalpindi",
            age: 22,
            gender: "Female",
            emergencyContact: "Usman Butt",
            emergencyPhone: "+923007889900",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Bilal",
            lastName: "Malik",
            phone: "+923007890123",
            email: "bilal.malik7@example.com",
            address: "34 Street 2, Lahore",
            age: 30,
            gender: "Male",
            emergencyContact: "Maryam Shah",
            emergencyPhone: "+923008990011",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Fatima",
            lastName: "Shah",
            phone: "+923008901234",
            email: "fatima.shah8@example.com",
            address: "67 Street 1, Karachi",
            age: 27,
            gender: "Female",
            emergencyContact: "Ali Khan",
            emergencyPhone: "+923009001122",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Usman",
            lastName: "Saeed",
            phone: "+923009012345",
            email: "usman.saeed9@example.com",
            address: "90 Street 4, Islamabad",
            age: 45,
            gender: "Male",
            emergencyContact: "Sara Ahmed",
            emergencyPhone: "+923001122334",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Maryam",
            lastName: "Butt",
            phone: "+923001123456",
            email: "maryam.butt10@example.com",
            address: "21 Street 5, Multan",
            age: 29,
            gender: "Female",
            emergencyContact: "Bilal Malik",
            emergencyPhone: "+923002233445",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Ali",
            lastName: "Saeed",
            phone: "+923001234570",
            email: "ali.saeed21@example.com",
            address: "19 Street 2, Karachi",
            age: 33,
            gender: "Male",
            emergencyContact: "Sara Malik",
            emergencyPhone: "+923009876510",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Sara",
            lastName: "Raza",
            phone: "+923001234571",
            email: "sara.raza22@example.com",
            address: "87 Street 3, Lahore",
            age: 26,
            gender: "Female",
            emergencyContact: "Usman Ali",
            emergencyPhone: "+923004556600",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Ahmed",
            lastName: "Malik",
            phone: "+923001234572",
            email: "ahmed.malik23@example.com",
            address: "51 Street 5, Islamabad",
            age: 41,
            gender: "Male",
            emergencyContact: "Fatima Qureshi",
            emergencyPhone: "+923006778810",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Zara",
            lastName: "Hussain",
            phone: "+923001234573",
            email: "zara.hussain24@example.com",
            address: "42 Street 4, Karachi",
            age: 24,
            gender: "Female",
            emergencyContact: "Hassan Shah",
            emergencyPhone: "+923005667712",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Hassan",
            lastName: "Qureshi",
            phone: "+923001234574",
            email: "hassan.qureshi25@example.com",
            address: "93 Street 2, Rawalpindi",
            age: 36,
            gender: "Male",
            emergencyContact: "Ayesha Khan",
            emergencyPhone: "+923007889932",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Ayesha",
            lastName: "Butt",
            phone: "+923001234575",
            email: "ayesha.butt26@example.com",
            address: "11 Street 3, Multan",
            age: 21,
            gender: "Female",
            emergencyContact: "Ali Ahmed",
            emergencyPhone: "+923008990013",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Bilal",
            lastName: "Saeed",
            phone: "+923001234576",
            email: "bilal.saeed27@example.com",
            address: "72 Street 1, Lahore",
            age: 38,
            gender: "Male",
            emergencyContact: "Maryam Malik",
            emergencyPhone: "+923009001145",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Fatima",
            lastName: "Malik",
            phone: "+923001234577",
            email: "fatima.malik28@example.com",
            address: "16 Street 5, Karachi",
            age: 30,
            gender: "Female",
            emergencyContact: "Ali Shah",
            emergencyPhone: "+923001112299",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Usman",
            lastName: "Hussain",
            phone: "+923001234578",
            email: "usman.hussain29@example.com",
            address: "88 Street 2, Lahore",
            age: 47,
            gender: "Male",
            emergencyContact: "Zara Butt",
            emergencyPhone: "+923002233411",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Maryam",
            lastName: "Shah",
            phone: "+923001234579",
            email: "maryam.shah30@example.com",
            address: "33 Street 1, Islamabad",
            age: 28,
            gender: "Female",
            emergencyContact: "Hassan Ali",
            emergencyPhone: "+923004556789",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Ali",
            lastName: "Hussain",
            phone: "+923001234580",
            email: "ali.hussain31@example.com",
            address: "20 Street 4, Karachi",
            age: 23,
            gender: "Male",
            emergencyContact: "Sara Qureshi",
            emergencyPhone: "+923009876520",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Sara",
            lastName: "Shah",
            phone: "+923001234581",
            email: "sara.shah32@example.com",
            address: "71 Street 3, Rawalpindi",
            age: 31,
            gender: "Female",
            emergencyContact: "Usman Khan",
            emergencyPhone: "+923005667701",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Ahmed",
            lastName: "Saeed",
            phone: "+923001234582",
            email: "ahmed.saeed33@example.com",
            address: "10 Street 1, Multan",
            age: 44,
            gender: "Male",
            emergencyContact: "Fatima Ahmed",
            emergencyPhone: "+923006778866",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Zara",
            lastName: "Khan",
            phone: "+923001234583",
            email: "zara.khan34@example.com",
            address: "96 Street 2, Lahore",
            age: 27,
            gender: "Female",
            emergencyContact: "Hassan Raza",
            emergencyPhone: "+923001112344",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Hassan",
            lastName: "Ahmed",
            phone: "+923001234584",
            email: "hassan.ahmed35@example.com",
            address: "54 Street 5, Islamabad",
            age: 39,
            gender: "Male",
            emergencyContact: "Ayesha Malik",
            emergencyPhone: "+923002233499",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Ayesha",
            lastName: "Raza",
            phone: "+923001234585",
            email: "ayesha.raza36@example.com",
            address: "83 Street 3, Karachi",
            age: 25,
            gender: "Female",
            emergencyContact: "Ali Hussain",
            emergencyPhone: "+923008990077",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Bilal",
            lastName: "Butt",
            phone: "+923001234586",
            email: "bilal.butt37@example.com",
            address: "28 Street 4, Islamabad",
            age: 37,
            gender: "Male",
            emergencyContact: "Maryam Saeed",
            emergencyPhone: "+923009001188",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Fatima",
            lastName: "Saeed",
            phone: "+923001234587",
            email: "fatima.saeed38@example.com",
            address: "67 Street 5, Lahore",
            age: 26,
            gender: "Female",
            emergencyContact: "Usman Malik",
            emergencyPhone: "+923001122355",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Ali",
            lastName: "Saeed",
            phone: "+923001234570",
            email: "ali.saeed21@example.com",
            address: "19 Street 2, Karachi",
            age: 33,
            gender: "Male",
            emergencyContact: "Sara Malik",
            emergencyPhone: "+923009876510",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Sara",
            lastName: "Raza",
            phone: "+923001234571",
            email: "sara.raza22@example.com",
            address: "87 Street 3, Lahore",
            age: 26,
            gender: "Female",
            emergencyContact: "Usman Ali",
            emergencyPhone: "+923004556600",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Ahmed",
            lastName: "Malik",
            phone: "+923001234572",
            email: "ahmed.malik23@example.com",
            address: "51 Street 5, Islamabad",
            age: 41,
            gender: "Male",
            emergencyContact: "Fatima Qureshi",
            emergencyPhone: "+923006778810",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Zara",
            lastName: "Hussain",
            phone: "+923001234573",
            email: "zara.hussain24@example.com",
            address: "42 Street 4, Karachi",
            age: 24,
            gender: "Female",
            emergencyContact: "Hassan Shah",
            emergencyPhone: "+923005667712",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Hassan",
            lastName: "Qureshi",
            phone: "+923001234574",
            email: "hassan.qureshi25@example.com",
            address: "93 Street 2, Rawalpindi",
            age: 36,
            gender: "Male",
            emergencyContact: "Ayesha Khan",
            emergencyPhone: "+923007889932",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Ayesha",
            lastName: "Butt",
            phone: "+923001234575",
            email: "ayesha.butt26@example.com",
            address: "11 Street 3, Multan",
            age: 21,
            gender: "Female",
            emergencyContact: "Ali Ahmed",
            emergencyPhone: "+923008990013",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Bilal",
            lastName: "Saeed",
            phone: "+923001234576",
            email: "bilal.saeed27@example.com",
            address: "72 Street 1, Lahore",
            age: 38,
            gender: "Male",
            emergencyContact: "Maryam Malik",
            emergencyPhone: "+923009001145",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Fatima",
            lastName: "Malik",
            phone: "+923001234577",
            email: "fatima.malik28@example.com",
            address: "16 Street 5, Karachi",
            age: 30,
            gender: "Female",
            emergencyContact: "Ali Shah",
            emergencyPhone: "+923001112299",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Usman",
            lastName: "Hussain",
            phone: "+923001234578",
            email: "usman.hussain29@example.com",
            address: "88 Street 2, Lahore",
            age: 47,
            gender: "Male",
            emergencyContact: "Zara Butt",
            emergencyPhone: "+923002233411",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Maryam",
            lastName: "Shah",
            phone: "+923001234579",
            email: "maryam.shah30@example.com",
            address: "33 Street 1, Islamabad",
            age: 28,
            gender: "Female",
            emergencyContact: "Hassan Ali",
            emergencyPhone: "+923004556789",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Ali",
            lastName: "Hussain",
            phone: "+923001234580",
            email: "ali.hussain31@example.com",
            address: "20 Street 4, Karachi",
            age: 23,
            gender: "Male",
            emergencyContact: "Sara Qureshi",
            emergencyPhone: "+923009876520",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Sara",
            lastName: "Shah",
            phone: "+923001234581",
            email: "sara.shah32@example.com",
            address: "71 Street 3, Rawalpindi",
            age: 31,
            gender: "Female",
            emergencyContact: "Usman Khan",
            emergencyPhone: "+923005667701",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Ahmed",
            lastName: "Saeed",
            phone: "+923001234582",
            email: "ahmed.saeed33@example.com",
            address: "10 Street 1, Multan",
            age: 44,
            gender: "Male",
            emergencyContact: "Fatima Ahmed",
            emergencyPhone: "+923006778866",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Zara",
            lastName: "Khan",
            phone: "+923001234583",
            email: "zara.khan34@example.com",
            address: "96 Street 2, Lahore",
            age: 27,
            gender: "Female",
            emergencyContact: "Hassan Raza",
            emergencyPhone: "+923001112344",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Hassan",
            lastName: "Ahmed",
            phone: "+923001234584",
            email: "hassan.ahmed35@example.com",
            address: "54 Street 5, Islamabad",
            age: 39,
            gender: "Male",
            emergencyContact: "Ayesha Malik",
            emergencyPhone: "+923002233499",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Ayesha",
            lastName: "Raza",
            phone: "+923001234585",
            email: "ayesha.raza36@example.com",
            address: "83 Street 3, Karachi",
            age: 25,
            gender: "Female",
            emergencyContact: "Ali Hussain",
            emergencyPhone: "+923008990077",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Bilal",
            lastName: "Butt",
            phone: "+923001234586",
            email: "bilal.butt37@example.com",
            address: "28 Street 4, Islamabad",
            age: 37,
            gender: "Male",
            emergencyContact: "Maryam Saeed",
            emergencyPhone: "+923009001188",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Fatima",
            lastName: "Saeed",
            phone: "+923001234587",
            email: "fatima.saeed38@example.com",
            address: "67 Street 5, Lahore",
            age: 26,
            gender: "Female",
            emergencyContact: "Usman Malik",
            emergencyPhone: "+923001122355",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Junaid",
            lastName: "Murtaza",
            phone: "03123456401",
            email: "junaid.murtaza@example.com",
            address: "Gulshan, Karachi",
            age: 27,
            gender: "Male",
            emergencyContact: "Kabir",
            emergencyPhone: "03124567890",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Tayyaba",
            lastName: "Qureshi",
            phone: "03211223449",
            email: "tayyaba.qureshi@example.com",
            address: "Model Town, Lahore",
            age: 22,
            gender: "Female",
            emergencyContact: "Ahsan",
            emergencyPhone: "03127654920",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Moosa",
            lastName: "Jatoi",
            phone: "03001221543",
            email: "moosa.jatoi@example.com",
            address: "Saddar, Karachi",
            age: 33,
            gender: "Male",
            emergencyContact: "Haroon",
            emergencyPhone: "03212785432",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Rimsha",
            lastName: "Nadeem",
            phone: "03334561234",
            email: "rimsha.nadeem@example.com",
            address: "Cantt, Lahore",
            age: 29,
            gender: "Female",
            emergencyContact: "Farooq",
            emergencyPhone: "03459872312",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Amaan",
            lastName: "Farooqi",
            phone: "03007654321",
            email: "amaan.farooqi@example.com",
            address: "Hyderi, Karachi",
            age: 26,
            gender: "Male",
            emergencyContact: "Khalid",
            emergencyPhone: "03127771234",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Maryam",
            lastName: "Shahid",
            phone: "03214487654",
            email: "maryam.shahid@example.com",
            address: "Bahria Town, Lahore",
            age: 32,
            gender: "Female",
            emergencyContact: "Shan",
            emergencyPhone: "03455341234",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Sufyan",
            lastName: "Kazmi",
            phone: "03122459871",
            email: "sufyan.kazmi@example.com",
            address: "North Karachi",
            age: 31,
            gender: "Male",
            emergencyContact: "Fawad",
            emergencyPhone: "03331239876",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Sadia",
            lastName: "Rauf",
            phone: "03451234234",
            email: "sadia.rauf@example.com",
            address: "DHA Phase 2, Karachi",
            age: 25,
            gender: "Female",
            emergencyContact: "Imran",
            emergencyPhone: "03132345432",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Danish",
            lastName: "Ghouri",
            phone: "03329871230",
            email: "danish.ghouri@example.com",
            address: "Shah Faisal Colony, Karachi",
            age: 30,
            gender: "Male",
            emergencyContact: "Akhtar",
            emergencyPhone: "03457896543",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Laiba",
            lastName: "Khalid",
            phone: "03004412987",
            email: "laiba.khalid@example.com",
            address: "Faisalabad City",
            age: 23,
            gender: "Female",
            emergencyContact: "Hassan",
            emergencyPhone: "03339987654",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Haris",
            lastName: "Samad",
            phone: "03211784532",
            email: "haris.samad@example.com",
            address: "Gulistan-e-Johar, Karachi",
            age: 34,
            gender: "Male",
            emergencyContact: "Adeel",
            emergencyPhone: "03021234567",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Zara",
            lastName: "Arif",
            phone: "03338887766",
            email: "zara.arif@example.com",
            address: "Bahadurabad, Karachi",
            age: 28,
            gender: "Female",
            emergencyContact: "Taimoor",
            emergencyPhone: "03121233445",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Farhan",
            lastName: "Dar",
            phone: "03456781234",
            email: "farhan.dar@example.com",
            address: "Johar Town, Lahore",
            age: 37,
            gender: "Male",
            emergencyContact: "Zahid",
            emergencyPhone: "03452347890",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Eman",
            lastName: "Qadri",
            phone: "03019998877",
            email: "eman.qadri@example.com",
            address: "Cantt, Karachi",
            age: 22,
            gender: "Female",
            emergencyContact: "Uzair",
            emergencyPhone: "03214567098",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Noman",
            lastName: "Ali",
            phone: "03134567812",
            email: "noman.ali@example.com",
            address: "Sadar, Rawalpindi",
            age: 33,
            gender: "Male",
            emergencyContact: "Sajid",
            emergencyPhone: "03029871230",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Sahar",
            lastName: "Usman",
            phone: "03221239876",
            email: "sahar.usman@example.com",
            address: "I-8 Islamabad",
            age: 29,
            gender: "Female",
            emergencyContact: "Rehan",
            emergencyPhone: "03022334466",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Bilal",
            lastName: "Mughal",
            phone: "03450001122",
            email: "bilal.mughal@example.com",
            address: "Garden East, Karachi",
            age: 36,
            gender: "Male",
            emergencyContact: "Sohail",
            emergencyPhone: "03217896543",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Ayesha",
            lastName: "Kamal",
            phone: "03330007744",
            email: "ayesha.kamal@example.com",
            address: "Phalia, Punjab",
            age: 27,
            gender: "Female",
            emergencyContact: "Ramzan",
            emergencyPhone: "03451239876",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Shayan",
            lastName: "Noor",
            phone: "03016665544",
            email: "shayan.noor@example.com",
            address: "Clifton, Karachi",
            age: 31,
            gender: "Male",
            emergencyContact: "Irfan",
            emergencyPhone: "03125554433",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Minal",
            lastName: "Javed",
            phone: "03452229988",
            email: "minal.javed@example.com",
            address: "Sargodha City",
            age: 24,
            gender: "Female",
            emergencyContact: "Ali",
            emergencyPhone: "03217778899",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Talha",
            lastName: "Rasheed",
            phone: "03123456780",
            email: "talha.rasheed@example.com",
            address: "G-10 Islamabad",
            age: 28,
            gender: "Male",
            emergencyContact: "Naveed",
            emergencyPhone: "03019998877",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Fatima",
            lastName: "Ansari",
            phone: "03334561239",
            email: "fatima.ansari@example.com",
            address: "Model Town, Lahore",
            age: 25,
            gender: "Female",
            emergencyContact: "Kashan",
            emergencyPhone: "03457778866",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Hadi",
            lastName: "Soomro",
            phone: "03005551234",
            email: "hadi.soomro@example.com",
            address: "Saddar, Hyderabad",
            age: 31,
            gender: "Male",
            emergencyContact: "Jalal",
            emergencyPhone: "03129871234",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Maheen",
            lastName: "Sadiq",
            phone: "03456667788",
            email: "maheen.sadiq@example.com",
            address: "PECHS, Karachi",
            age: 27,
            gender: "Female",
            emergencyContact: "Ayaz",
            emergencyPhone: "03325554433",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Khalid",
            lastName: "Mirza",
            phone: "03211223344",
            email: "khalid.mirza@example.com",
            address: "Gulshan-e-Maymar, Karachi",
            age: 36,
            gender: "Male",
            emergencyContact: "Rashid",
            emergencyPhone: "03051234567",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Aqsa",
            lastName: "Baloch",
            phone: "03334445566",
            email: "aqsa.baloch@example.com",
            address: "DHA Phase 5, Karachi",
            age: 29,
            gender: "Female",
            emergencyContact: "Sami",
            emergencyPhone: "03440007788",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Zeeshan",
            lastName: "Hassan",
            phone: "03017778899",
            email: "zeeshan.hassan@example.com",
            address: "Rawalpindi City",
            age: 34,
            gender: "Male",
            emergencyContact: "Faisal",
            emergencyPhone: "03339990011",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Sahar",
            lastName: "Baig",
            phone: "03450004455",
            email: "sahar.baig@example.com",
            address: "DHA Phase 3, Lahore",
            age: 26,
            gender: "Female",
            emergencyContact: "Yasir",
            emergencyPhone: "03016664422",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Imran",
            lastName: "Naseer",
            phone: "03126667777",
            email: "imran.naseer@example.com",
            address: "Landhi, Karachi",
            age: 32,
            gender: "Male",
            emergencyContact: "Furqan",
            emergencyPhone: "03453332211",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Mahnoor",
            lastName: "Iqbal",
            phone: "03335556677",
            email: "mahnoor.iqbal@example.com",
            address: "Iqbal Town, Lahore",
            age: 24,
            gender: "Female",
            emergencyContact: "Zaim",
            emergencyPhone: "03229998877",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Rizwan",
            lastName: "Jamal",
            phone: "03025553344",
            email: "rizwan.jamal@example.com",
            address: "Sialkot City",
            age: 37,
            gender: "Male",
            emergencyContact: "Shahid",
            emergencyPhone: "03127774455",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Hafsa",
            lastName: "Rehman",
            phone: "03458889900",
            email: "hafsa.rehman@example.com",
            address: "F-11 Islamabad",
            age: 28,
            gender: "Female",
            emergencyContact: "Hammad",
            emergencyPhone: "03334446622",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Sarim",
            lastName: "Yousuf",
            phone: "03123335577",
            email: "sarim.yousuf@example.com",
            address: "Malir, Karachi",
            age: 30,
            gender: "Male",
            emergencyContact: "Arsalan",
            emergencyPhone: "03014445566",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Nimra",
            lastName: "Azam",
            phone: "03215556677",
            email: "nimra.azam@example.com",
            address: "Cantt, Peshawar",
            age: 27,
            gender: "Female",
            emergencyContact: "Jibran",
            emergencyPhone: "03459998877",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Ahmad",
            lastName: "Usmani",
            phone: "03019995522",
            email: "ahmad.usmani@example.com",
            address: "Garden West, Karachi",
            age: 35,
            gender: "Male",
            emergencyContact: "Kamran",
            emergencyPhone: "03218887766",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Noor",
            lastName: "Shafqat",
            phone: "03457772211",
            email: "noor.shafqat@example.com",
            address: "DHA Phase 6, Lahore",
            age: 23,
            gender: "Female",
            emergencyContact: "Musa",
            emergencyPhone: "03120009988",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Adeel",
            lastName: "Khattak",
            phone: "03128889900",
            email: "adeel.khattak@example.com",
            address: "Hayatabad, Peshawar",
            age: 33,
            gender: "Male",
            emergencyContact: "Sohail",
            emergencyPhone: "03335554433",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Zunaira",
            lastName: "Nawaz",
            phone: "03334443322",
            email: "zunaira.nawaz@example.com",
            address: "Faisalabad City",
            age: 29,
            gender: "Female",
            emergencyContact: "Rahim",
            emergencyPhone: "03457775544",
            priority: "High",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Hamza",
            lastName: "Mehmood",
            phone: "03024443355",
            email: "hamza.mehmood@example.com",
            address: "Gulistan-e-Johar, Karachi",
            age: 31,
            gender: "Male",
            emergencyContact: "Anees",
            emergencyPhone: "03126667711",
            priority: "Medium",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            firstName: "Alishba",
            lastName: "Shamim",
            phone: "03453332211",
            email: "alishba.shamim@example.com",
            address: "Model Town, Lahore",
            age: 26,
            gender: "Female",
            emergencyContact: "Zayan",
            emergencyPhone: "03215556622",
            priority: "Low",
            createdAt: new Date(),
            updatedAt: new Date()
        }


    ]

const transformedPatients = patientData.map(p => {
  const { firstName, lastName, ...rest } = p; // extract first and last
  return {
    fullName: `${firstName} ${lastName}`, // new field
    ...rest // keep other fields
  };
});

// Find a document in a collection.
db.getCollection("patientvisits").deleteMany({});
// db.getCollection("patients").insertMany(transformedPatients);
// db.getCollection("patients").find();